"""Workflow product integration contracts for the SAGE serving surface."""

from .contracts import (
    COMFY_FIRST_EXTENSION_POINT,
    LANGGRAPH_SECOND_EXTENSION_POINT,
    WORKFLOW_INTEGRATION_SCHEMA_VERSION,
    ImportedWorkflow,
    WorkflowExecutionTarget,
    WorkflowExecutionTargetType,
    WorkflowImportRequest,
    WorkflowImportResponse,
    WorkflowIntegrationExtensionPoint,
    WorkflowIntegrationOperation,
    WorkflowIntegrationRequest,
    WorkflowIntegrationResponse,
    WorkflowJobResultCollectRequest,
    WorkflowJobResultCollectResponse,
    WorkflowJobStatus,
    WorkflowJobStatusPollRequest,
    WorkflowJobStatusPollResponse,
    WorkflowJobSubmitRequest,
    WorkflowJobSubmitResponse,
    WorkflowProductAdapter,
    WorkflowProductAdapterDescriptor,
    WorkflowServingRequestContext,
    WorkflowSubmitMode,
    default_workflow_product_extension_points,
)
from .mock import MockSageExecutable, MockWorkflowProductAdapter
from .registry import (
    WorkflowIntegrationRegistry,
    build_workflow_integration_registry_from_env,
    validate_workflow_product_adapter,
)
from .service_modes import (
    ApplicationServiceContract,
    ServiceMode,
    ServiceRuntimeSnapshot,
    compile_service_contract,
    fetch_vllm_runtime_snapshot,
    parse_vllm_metrics,
    validate_mode_decision,
)

__all__ = [
    "COMFY_FIRST_EXTENSION_POINT",
    "ImportedWorkflow",
    "LANGGRAPH_SECOND_EXTENSION_POINT",
    "MockSageExecutable",
    "MockWorkflowProductAdapter",
    "WORKFLOW_INTEGRATION_SCHEMA_VERSION",
    "WorkflowExecutionTarget",
    "WorkflowExecutionTargetType",
    "WorkflowImportRequest",
    "WorkflowImportResponse",
    "WorkflowIntegrationExtensionPoint",
    "WorkflowIntegrationOperation",
    "WorkflowIntegrationRegistry",
    "WorkflowIntegrationRequest",
    "WorkflowIntegrationResponse",
    "WorkflowServingRequestContext",
    "WorkflowJobResultCollectRequest",
    "WorkflowJobResultCollectResponse",
    "WorkflowJobStatus",
    "WorkflowJobStatusPollRequest",
    "WorkflowJobStatusPollResponse",
    "WorkflowJobSubmitRequest",
    "WorkflowJobSubmitResponse",
    "WorkflowProductAdapter",
    "WorkflowProductAdapterDescriptor",
    "WorkflowSubmitMode",
    "build_workflow_integration_registry_from_env",
    "ApplicationServiceContract",
    "ServiceMode",
    "ServiceRuntimeSnapshot",
    "compile_service_contract",
    "default_workflow_product_extension_points",
    "fetch_vllm_runtime_snapshot",
    "parse_vllm_metrics",
    "validate_mode_decision",
    "validate_workflow_product_adapter",
]
